kind: Deployment
apiVersion: apps/v1
metadata:
  name: quarkus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
        - name: app
          image: quay.io/bhouse/quarkus-bootstrap-jvm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: public