kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: quarkus-template
  namespace: <YOUR NAMESPACE HERE>
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: quarkus-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: quarkus
      template:
        metadata:
          labels:
            app: quarkus
        spec:
          containers:
            - name: app
              image: quay.io/bhouse/quarkus-bootstrap-jvm:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  name: public
  - kind: Service
    apiVersion: v1
    metadata:
      name: quarkus-service
    spec:
      selector:
        app: quarkus
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
  - kind: Secret
    apiVersion: v1
    metadata:
      name: psql-secrets
    type: Opaque
    stringData:
      POSTGRESQL_ADMIN_PASSWORD: postgres
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USER: postgres
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: psql-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: brightly-general-purpose
      volumeMode: Filesystem
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: psql-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: psql
      template:
        metadata:
          labels:
            app: psql
        spec:
          containers:
            - name: psql
              image: registry.redhat.io/rhel8/postgresql-12:1-109.1655143367
              imagePullPolicy: Always
              ports:
                - containerPort: 5432
                  name: public
              env:
                - name: POSTGRESQL_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: psql-secrets
                      key: POSTGRESQL_ADMIN_PASSWORD
                      optional: false
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: psql-secrets
                      key: POSTGRESQL_PASSWORD
                      optional: false
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: psql-secrets
                      key: POSTGRESQL_DATABASE
                      optional: false
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: psql-secrets
                      key: POSTGRESQL_USER
                      optional: false
              volumeMounts:
                - mountPath: /var/lib/pgsql/data
                  name: psql-data
          volumes:
            - name: psql-data
              persistentVolumeClaim:
                claimName: psql-pvc
  - kind: Service
    apiVersion: v1
    metadata:
      name: postgresql    # must match the name of the PostgreSQL server in the connection string defined in the appsettings.json
    spec:
      selector:
        app: psql
      ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432