kind: Secret
apiVersion: v1
metadata:
  name: db-secrets
type: Opaque
stringData:
  POSTGRESQL_ADMIN_PASSWORD: postgres
  POSTGRESQL_PASSWORD: root
  POSTGRESQL_DATABASE: postgres
  POSTGRESQL_USER: postgres